### ISSUE TITLE
Difficulty in interpreting the output result

### ISSUE THREAD

**Issue by khatiaxomiya** [JoshuaSBrown/QC_Tools#50]
Hi there, I have run the following file to determine the charge transfer integral between HOMO and HOMO-1. My aim is to calculate the **hole transfer integral**. Can you please explain what is J_ab, e_a, e_b, S_ab. I also need the site energy values. Is the site energies are the energy of HOMO and HOMO-1 of the dimer?

```
calc_J -p_1 NitroBenzene_Parent.pun -orb_ty_1 HOMO -p_2 Monomer2_NitroBenzene_P1.pun -orb_ty_2 HOMO -orb_num_1 -1 -p_P NitroBenzene_P1.pun

Running calc_J VERSION 1.5
log file for first monomer is:      NitroBenzene_Parent.log
log file for second monomer is:     Monomer2_NitroBenzene_P1.log
log file for dimer is:              NitroBenzene_P1.log
pun file for the first monomer is:  NitroBenzene_Parent.pun
pun file for the second monomer is: Monomer2_NitroBenzene_P1.pun
pun file for the dimer is:          NitroBenzene_P1.pun

Dimer     Spin Alpha
Monomer 1 Spin Alpha Orbital HOMO-1
Monomer 2 Spin Alpha Orbital HOMO
J_ab  0.0303874 eV
e_a   -8.24176 eV
e_b   -8.11605 eV
S_ab  -0.00203265
J_eff 0.0137626 eV
```

**Comment by JoshuaSBrown** [comment]
J_ab and e_a are essentially the coulomb and resonance/charge transfer integrals of each of the molecules, you can take a look at the Huckel method to get an idea of what they are https://chem.libretexts.org/Bookshelves/Inorganic_Chemistry/Map%3A_Inorganic_Chemistry_(Housecroft)/04%3A_Experimental_techniques/4.13%3A_Computational_Methods/4.13C%3A_H%C3%BCckel_MO_Theory

I will summarize for you the coulomb integrals are a negative energy e_a and e_b associated with how well the charges are bound. In this case because you are dealing with molecular orbitals e_a and e_b describe how strongly bound the charge is to molecule A and molecule B respectively. The J_ab resonance/transfer integrals are a measure of how the molecules interact. 

J_ab, e_a and e_b represent the coulomb and transfer integrals before the basis set has been orthogonalized. In other words more math needs to be done to get the right values. When you orthogonalize these values you end up with the correct values. 

J_eff - which is the transfer integral
e_a_eff, e_b_eff - which are equivalent to the site energies, they are not calculated, (will add to my to do list)

To calculate e_a_eff, e_b_eff you can use equation 10 from this paper. 

https://pubs.rsc.org/en/content/articlelanding/2010/cp/c002337j/unauth#!divAbstract

If you want to calculate hole transport the ideal way to do this would be to calculate the cations of molecule A and molecule B with the cation of the Dimer. Then you would use the LUMO of both monomers and the LUMO of the dimer. 

However, this is a bit complicated because instead of dealing with closed shells you have to use unrestricted shells. A good approximation to this is to use the HOMO of both molecules and the HOMO of the dimer all in the neutral state. This is what is shown in the tutorial I believe. 

Does this make sense?

**Comment by khatiaxomiya** [comment]
Thank you very much for your insightful comment. 

From this equation, we will get both **e_a_eff**, **e_b_eff** value to be same for hole transport. Similarly **e_a_eff**, **e_b_eff**  will be same for electron transport. Am I right in saying so?

**Comment by khatiaxomiya** [comment]
How can I find **e_b_eff**? But, in the paper by Baumeier et.al. they got different values of **e_a_eff, e_b_eff** . Do I need to interchange **e_a** and **e_b** in the equation 10 of the above paper?

**Comment by JoshuaSBrown** [comment]
e_a_eff and e_b_eff will only be the same if the molecules are chemically and spatially symmetric. What systems are you looking at specifically? If you are getting different values than Baumeier for the same system that is problematic.

**Comment by JoshuaSBrown** [comment]
Yes, as long as you are dealing with chemically and spatially symmetric systems e_a and e_b should be the same, with the condition that you are also using the same molecular orbitals. I.e. for hole transport you are using the HOMO of molecule A and the HOMO of molecule B, for electron transport you are using the LUMO of molecule A, and the LUMO of molecule B.

**Comment by khatiaxomiya** [comment]
My system is different from the one discussed in that paper. But how one can get different values of effective site energies e_a_eff and e_b_eff, as we are using the same equation to find them (equation 10).

**Comment by khatiaxomiya** [comment]
I mean do I have to do (e_b - e_a) instead of (e_a - e_b) to find e_b_eff?

**Comment by JoshuaSBrown** [comment]
1. where in the Baumeier paper are you seeing that they get different values for e_A and e_B. 
2. equation 10 is correct, I can show you how to work it out from scratch if you want. 
3. You will only get different values for e_a_eff and e_b_eff if e_a and e_b are different. The only time e_a and e_b will actually be the same is if your molecules are chemically and spatially symmetric and you are dealing the the same orbitals (HOMO mol A, HOMO mol B, etc...). Is this true for your case?
